version: "3"

services:

  tinyproxy:
    image: dannydirect/tinyproxy:latest
    container_name: tinyproxy
    environment:
      - BASIC_AUTH_USER=user
      - BASIC_AUTH_PASSWORD=password
    ports:
      - 8888:8888
    command:
      - ANY
    tty: false

  lusid-sdk-python-test:
    build: .
    container_name: lusid-sdk-python-preview-test
    image: finbourne/lusid-sdk-python-preview-test
    environment:
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_LUSID_API_URL=${FBN_BASE_API_URL}/api
      - FBN_PASSWORD
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PROXY_ADDRESS=http://tinyproxy:8888
      - FBN_PROXY_USERNAME=user
      - FBN_PROXY_PASSWORD=password
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src
    depends_on:
      - tinyproxy